### ISSUE TITLE
[IdleValue] Add valueOf method

### ISSUE THREAD

**Issue by pdf13** [GoogleChromeLabs/idlize#10]
Hi @philipwalton! Congratulations for your work on this lib!

I would like to suggest two possible improvements to IdleValue class. The first one came from the concept that JS Object prototype has a method called `valueOf`[1] that converts the object to a primitive value. I think that it can be very useful  because it will allow code to behave like this:

```js
const myIdleValue = new IdleValue(() => return 'example');
console.log(myIdleValue === 'example'); // true
console.log('my ' + myIdleValue); // my example
```

The second possible change is an approach closer of the actual implementation. `getValue` and `setValue` methods can be transformed in getter and setter methods.

```js
class IdleValue {
   constructor(init) {
     // (...)
  }

  get value() {
    if (this.value_ === undefined) {
      this.cancleIdleInit_();
      this.value_ = this.init_();
    }
    return this.value_;
  }

  set value(param) {
    this.cancleIdleInit_();
    this.value_ = newValue;
  }

  cancleIdleInit_() {
    // (...)
  }
}
```

or even like this, if you want to keep compatibility with `getValue` and `setValue` methods

```js
class IdleValue {
   constructor(init) {
     // (...)
  }

  get value() {
   this.getValue();
  }

  set value(param) {
    this.setValue(param);
  }

  getValue() {
    // (...)
  }

  setValue(param) {
    // (...)
  }

  cancleIdleInit_() {
    // (...)
  }
}
```

So the example will be:

```js
const myIdleValue = new IdleValue(() => return 'example');
console.log(myIdleValue.value === 'example'); // true
console.log('my ' + myIdleValue.value); // my example
myIdleValue.value = 'new example';
console.log(myIdleValue) // new example
```

[1] [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf)

**Comment by philipwalton** [comment]
I considered the `valueOf` approach when developing the library, but it would only work for primitive objects, so it wouldn't be foolproof.

**Comment by pdf13** [comment]
@philipwalton even suggesting the `valueOf` solution, I know that it is not perfect. Because of this, I add a `getter/setter` approach. What do you think? We can add it without breaking the module API for now, and remove the old methods later or even keep booth.

**Comment by philipwalton** [comment]
Yep, that's [what I do here](https://github.com/googleanalytics/autotrack/blob/703ee09/lib/session.js#L119-L127). I use the `IdleValue` class under the hood, but I expose it through a getter so the API doesn't change.

**Comment by philipwalton** [comment]
I'm going to close this issue as I don't think `valueOf` is a viable option unfortunately.
