### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by alejandronanez** [GoogleChromeLabs/idlize#7]
Hello, first of all, thanks for making `idlize`!

I see that you suggest to use `npm install -D idlize` in order to install the library, is there a reason for that? I think it should be added as `npm install idlize / yarn add idlize`.

If that's the case, I can create a PR for it!

Thanks again,

**Comment by alejandronanez** [comment]
Yeah since you’re not using for development only (it will affect your production build)

A good example of a devDependency could be `webpack`.

**Comment by pietrofxq** [comment]
Agreed, I don't think there's any case where someone would use this as a dev dependency. Dev deps are not ran in browsers, and this package is definitely for code that runs there.

**Comment by philipwalton** [comment]
Closed via #9.
